# Generated by Django 3.2.12 on 2022-02-22 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('programming', 'Programming'), ('health', 'Health'), ('environment', 'Environment'), ('business', 'Business'), ('style', 'Style'), ('travel', 'Travel'), ('opinion', 'Opinion')], default='technology', max_length=50)),
                ('thumbnail', models.ImageField(upload_to='blogimages/')),
                ('excerpt', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
