# Generated by Django 3.2.12 on 2022-02-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='year',
            field=models.CharField(default=2022, max_length=4),
            preserve_default=False,
        ),
    ]
